import {
  AdminCourseAssignmentAuditEvent,
  AdminCourseMemberBinding,
  AdminCourseWorkspaceCourse,
  AdminCourseWorkspaceUser,
  AdminScheduleEvent,
} from "../admin/admin.types";
import { AttendanceDatabase } from "../attendance/attendance.types";
import { AssignmentDatabase } from "../assignments/assignment.types";
import { CoursesDatabase, StoredCourseRecord } from "../courses/courses.types";
import { EnrollmentsDatabase, StoredEnrollmentRecord } from "../enrollments/enrollments.types";
import { StoredFileRecord } from "../files/files.types";
import { RawUserSeed, StoredUserRecord, UsersDatabase } from "../users/users.types";

interface AdminSeedData {
  users: AdminCourseWorkspaceUser[];
  courses: AdminCourseWorkspaceCourse[];
  memberBindings: AdminCourseMemberBinding[];
  schedules: AdminScheduleEvent[];
  courseAssignmentAuditEvents: AdminCourseAssignmentAuditEvent[];
}

const adminSeedData: AdminSeedData = {
  users: [
    {
      userId: "instructor-민수-김",
      userName: "민수 김",
      birthDate: "1989-02-14",
      title: "Frontend Engineer",
      defaultRole: "INSTRUCTOR",
    },
    {
      userId: "instructor-정하늘",
      userName: "정하늘",
      birthDate: "1990-05-21",
      title: "Senior Frontend Developer",
      defaultRole: "INSTRUCTOR",
    },
    {
      userId: "instructor-이도현",
      userName: "이도현",
      birthDate: "1987-09-17",
      title: "Backend Architect",
      defaultRole: "INSTRUCTOR",
    },
    {
      userId: "instructor-박서윤",
      userName: "박서윤",
      birthDate: "1991-11-05",
      title: "AI Product Designer",
      defaultRole: "INSTRUCTOR",
    },
    {
      userId: "instructor-한지민",
      userName: "한지민",
      birthDate: "1988-04-02",
      title: "Data Analyst",
      defaultRole: "INSTRUCTOR",
    },
    {
      userId: "instructor-윤태호",
      userName: "윤태호",
      birthDate: "1992-12-19",
      title: "Product Designer",
      defaultRole: "INSTRUCTOR",
    },
    {
      userId: "instructor-dev-01",
      userName: "개발용 강사",
      birthDate: "1990-01-30",
      title: "Instructor",
      defaultRole: "INSTRUCTOR",
    },
    {
      userId: "assistant-dev-01",
      userName: "개발용 조교",
      birthDate: "1996-11-02",
      title: "Assistant",
      defaultRole: "ASSISTANT",
    },
    {
      userId: "student-demo-01",
      userName: "데모 수강생",
      birthDate: "1998-04-05",
      title: "수강생",
      defaultRole: "STUDENT",
    },
    {
      userId: "student-kim-hana",
      userName: "김하나",
      birthDate: "2001-04-15",
      title: "수강생",
      defaultRole: "STUDENT",
    },
    {
      userId: "student-lee-jisoo",
      userName: "이지수",
      birthDate: "1998-03-18",
      title: "수강생",
      defaultRole: "STUDENT",
    },
  ],
  courses: [
    {
      courseId: "course-next-ai-lms",
      courseTitle: "Next.js로 시작하는 AI LMS 프론트엔드",
      category: "프론트엔드",
      classScope: "nextjs로-시작하는-ai-lms-프론트엔드",
      status: "ACTIVE",
      sectionLabel: "1반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-04-20",
      endDate: "2026-07-12",
      enrollmentStartDate: "2026-03-30",
      enrollmentEndDate: "2026-04-27",
      pacingType: "INSTRUCTOR_PACED",
    },
    {
      courseId: "course-react-state",
      courseTitle: "React 상태 설계 패턴",
      category: "프론트엔드",
      classScope: "react-상태-설계-패턴",
      status: "ACTIVE",
      sectionLabel: "2반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-04-27",
      endDate: "2026-07-19",
      enrollmentStartDate: "2026-04-06",
      enrollmentEndDate: "2026-05-04",
      pacingType: "INSTRUCTOR_PACED",
    },
    {
      courseId: "course-spring-lms-api",
      courseTitle: "Spring으로 만드는 LMS API 설계",
      category: "백엔드",
      classScope: "spring으로-만드는-lms-api-설계",
      status: "PENDING",
      sectionLabel: "3반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-05-04",
      endDate: "2026-07-26",
      enrollmentStartDate: "2026-04-13",
      enrollmentEndDate: "2026-05-11",
      pacingType: "INSTRUCTOR_PACED",
    },
    {
      courseId: "course-llm-study-assistant",
      courseTitle: "LLM 학습 도우미 UI 설계",
      category: "AI 활용",
      classScope: "llm-학습-도우미-ui-설계",
      status: "ACTIVE",
      sectionLabel: "4반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-05-11",
      endDate: "2026-08-02",
      enrollmentStartDate: "2026-04-20",
      enrollmentEndDate: "2026-05-18",
      pacingType: "INSTRUCTOR_PACED",
    },
    {
      courseId: "course-sql-learning-analytics",
      courseTitle: "SQL로 보는 학습 분석",
      category: "데이터",
      classScope: "sql로-보는-학습-분석",
      status: "ACTIVE",
      sectionLabel: "5반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-05-18",
      endDate: "2026-08-09",
      enrollmentStartDate: "2026-04-27",
      enrollmentEndDate: "2026-05-25",
      pacingType: "INSTRUCTOR_PACED",
    },
    {
      courseId: "course-design-system-edu",
      courseTitle: "교육 제품용 디자인 시스템",
      category: "디자인 시스템",
      classScope: "교육-제품용-디자인-시스템",
      status: "ACTIVE",
      sectionLabel: "6반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-05-25",
      endDate: "2026-08-16",
      enrollmentStartDate: "2026-05-04",
      enrollmentEndDate: "2026-06-01",
      pacingType: "INSTRUCTOR_PACED",
    },
    {
      courseId: "course-ai-product-engineering-3",
      courseTitle: "AI Product Engineering 3기",
      category: "AI 개발",
      classScope: "ai-product-engineering-3",
      status: "ACTIVE",
      sectionLabel: "3기 A반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-04-01",
      endDate: "2026-06-23",
      enrollmentStartDate: "2026-03-10",
      enrollmentEndDate: "2026-04-08",
      pacingType: "INSTRUCTOR_PACED",
    },
  ],
  memberBindings: [
    { courseId: "course-next-ai-lms", userId: "instructor-민수-김", role: "INSTRUCTOR" },
    { courseId: "course-react-state", userId: "instructor-정하늘", role: "INSTRUCTOR" },
    { courseId: "course-spring-lms-api", userId: "instructor-이도현", role: "INSTRUCTOR" },
    {
      courseId: "course-llm-study-assistant",
      userId: "instructor-박서윤",
      role: "INSTRUCTOR",
    },
    {
      courseId: "course-sql-learning-analytics",
      userId: "instructor-한지민",
      role: "INSTRUCTOR",
    },
    {
      courseId: "course-design-system-edu",
      userId: "instructor-윤태호",
      role: "INSTRUCTOR",
    },
    {
      courseId: "course-ai-product-engineering-3",
      userId: "instructor-dev-01",
      role: "INSTRUCTOR",
    },
    { courseId: "course-ai-product-engineering-3", userId: "assistant-dev-01", role: "ASSISTANT" },
    { courseId: "course-next-ai-lms", userId: "student-demo-01", role: "STUDENT" },
    { courseId: "course-next-ai-lms", userId: "student-kim-hana", role: "STUDENT" },
    { courseId: "course-spring-lms-api", userId: "student-kim-hana", role: "STUDENT" },
    { courseId: "course-llm-study-assistant", userId: "student-demo-01", role: "STUDENT" },
    { courseId: "course-llm-study-assistant", userId: "student-lee-jisoo", role: "STUDENT" },
    {
      courseId: "course-ai-product-engineering-3",
      userId: "student-demo-01",
      role: "STUDENT",
    },
  ],
  schedules: [
    {
      id: "orientation-week-2",
      title: "오리엔테이션 및 학습 가이드",
      categoryLabel: "운영",
      dateKey: "2026-04-08",
      dateLabel: "4월 8일 수요일",
      timeLabel: "09:30 - 11:00",
      locationLabel: "온라인 라이브 · Zoom A",
      visibilityType: "global",
      visibilityScope: "global",
      visibilityLabel: "학원 전체 행사",
      requiresAttendanceCheck: false,
      sourceType: "SYSTEM",
    },
    {
      id: "attendance-morning-1",
      title: "오전 출석 체크",
      categoryLabel: "필수 출석",
      dateKey: "2026-04-08",
      dateLabel: "4월 8일 수요일",
      timeLabel: "09:00 - 09:20",
      locationLabel: "8층 AI 강의실",
      visibilityType: "class",
      visibilityScope: "ai-product-engineering-3",
      visibilityLabel: "AI Product Engineering 3기 수업",
      requiresAttendanceCheck: true,
      attendanceWindowLabel: "09:20까지 인증 가능",
      attendanceWindowStartAt: "2026-04-08T09:00:00+09:00",
      attendanceWindowEndAt: "2026-04-08T09:20:00+09:00",
      sourceType: "SYSTEM",
    },
    {
      id: "frontend-lab",
      title: "프론트엔드 실습 랩",
      categoryLabel: "수업",
      dateKey: "2026-04-08",
      dateLabel: "4월 8일 수요일",
      timeLabel: "10:00 - 12:30",
      locationLabel: "8층 AI 강의실",
      visibilityType: "class",
      visibilityScope: "ai-product-engineering-3",
      visibilityLabel: "AI Product Engineering 3기 수업",
      requiresAttendanceCheck: false,
      sourceType: "SYSTEM",
    },
    {
      id: "career-coaching",
      title: "커리어 코칭 데이",
      categoryLabel: "특강",
      dateKey: "2026-04-10",
      dateLabel: "4월 10일 금요일",
      timeLabel: "14:00 - 16:00",
      locationLabel: "온라인 라이브 · Meet",
      visibilityType: "global",
      visibilityScope: "global",
      visibilityLabel: "학원 전체 행사",
      requiresAttendanceCheck: false,
      sourceType: "SYSTEM",
    },
    {
      id: "attendance-afternoon-missed",
      title: "오후 출석 체크",
      categoryLabel: "필수 출석",
      dateKey: "2026-04-07",
      dateLabel: "4월 7일 화요일",
      timeLabel: "13:00 - 13:20",
      locationLabel: "8층 AI 강의실",
      visibilityType: "class",
      visibilityScope: "ai-product-engineering-3",
      visibilityLabel: "AI Product Engineering 3기 수업",
      requiresAttendanceCheck: true,
      attendanceWindowLabel: "13:20까지 인증 가능",
      attendanceWindowStartAt: "2026-04-07T13:00:00+09:00",
      attendanceWindowEndAt: "2026-04-07T13:20:00+09:00",
      sourceType: "SYSTEM",
    },
    {
      id: "attendance-evening-1",
      title: "종료 전 출석 확인",
      categoryLabel: "필수 출석",
      dateKey: "2026-04-08",
      dateLabel: "4월 8일 수요일",
      timeLabel: "17:40 - 18:00",
      locationLabel: "8층 AI 강의실",
      visibilityType: "class",
      visibilityScope: "ai-product-engineering-3",
      visibilityLabel: "AI Product Engineering 3기 수업",
      requiresAttendanceCheck: true,
      attendanceWindowLabel: "18:00까지 인증 가능",
      attendanceWindowStartAt: "2026-04-08T17:40:00+09:00",
      attendanceWindowEndAt: "2026-04-08T18:00:00+09:00",
      sourceType: "SYSTEM",
    },
  ],
  courseAssignmentAuditEvents: [
    {
      id: "audit-submission-1",
      courseId: "course-next-ai-lms",
      assignmentId: "assignment-next-auth-flow",
      assignmentTitle: "인증 플로우 UI/상태 분리",
      submissionId: "submission-1",
      actorId: "student-kim-hana",
      actorName: "김하나",
      actorRole: "STUDENT",
      action: "SUBMITTED",
      occurredAt: "2026-04-08T00:00:00.000Z",
      note: "초기 제출",
    },
    {
      id: "audit-submission-2-r3",
      courseId: "course-llm-study-assistant",
      assignmentId: "assignment-llm-study-assistant",
      assignmentTitle: "학습 도우미 패널 인터랙션 개선",
      submissionId: "submission-2-r3",
      actorId: "student-demo-01",
      actorName: "데모 수강생",
      actorRole: "STUDENT",
      action: "RESUBMITTED",
      occurredAt: "2026-04-09T01:15:00.000Z",
      note: "3차 재제출",
    },
    {
      id: "audit-feedback-2-r3",
      courseId: "course-llm-study-assistant",
      assignmentId: "assignment-llm-study-assistant",
      assignmentTitle: "학습 도우미 패널 인터랙션 개선",
      submissionId: "submission-2-r3",
      actorId: "instructor-민수-김",
      actorName: "민수 김",
      actorRole: "INSTRUCTOR",
      action: "FEEDBACK_ADDED",
      occurredAt: "2026-04-09T01:30:00.000Z",
      note: "리뷰 완료 코멘트",
    },
    {
      id: "audit-review-4",
      courseId: "course-spring-lms-api",
      assignmentId: "assignment-spring-api-contract",
      assignmentTitle: "출석 API 계약 문서화",
      submissionId: "submission-4",
      actorId: "instructor-민수-김",
      actorName: "민수 김",
      actorRole: "INSTRUCTOR",
      action: "REVIEW_STATUS_CHANGED",
      occurredAt: "2026-04-09T04:10:00.000Z",
      note: "리뷰 완료",
    },
  ],
};

const assignmentSeedData: AssignmentDatabase = {
  students: [
    {
      id: "student-demo-01",
      name: "데모 수강생",
      enrolledCourseIds: ["course-next-ai-lms", "course-llm-study-assistant"],
    },
    {
      id: "student-kim-hana",
      name: "김하나",
      enrolledCourseIds: ["course-next-ai-lms", "course-spring-lms-api"],
    },
    {
      id: "student-lee-jisoo",
      name: "이지수",
      enrolledCourseIds: ["course-llm-study-assistant"],
    },
  ],
  assignments: [
    {
      id: "assignment-next-auth-flow",
      courseId: "course-next-ai-lms",
      courseTitle: "Next.js로 시작하는 AI LMS 프론트엔드",
      title: "인증 플로우 UI/상태 분리",
      prompt: "로그인-세션-권한 가드 흐름을 feature 단위로 분리하고 PR 설명을 작성하세요.",
      dueAt: "2026-04-12T09:00:00.000Z",
      createdAt: "2026-04-09T00:00:00.000Z",
      allowFileUpload: true,
      allowCodeEditor: true,
    },
    {
      id: "assignment-next-course-filter",
      courseId: "course-next-ai-lms",
      courseTitle: "Next.js로 시작하는 AI LMS 프론트엔드",
      title: "서버 필터 스키마 안정화",
      prompt: "검색/필터 응답 스키마를 고정하고 타입/정규화 로직을 정리하세요.",
      dueAt: "2026-04-15T09:00:00.000Z",
      createdAt: "2026-04-09T05:00:00.000Z",
      allowFileUpload: true,
      allowCodeEditor: true,
    },
    {
      id: "assignment-llm-study-assistant",
      courseId: "course-llm-study-assistant",
      courseTitle: "LLM 학습 도우미 UI 설계",
      title: "학습 도우미 패널 인터랙션 개선",
      prompt: "학습 요약/후속 질문 플로우를 개선하고 사용자 테스트 메모를 남기세요.",
      dueAt: "2026-04-14T09:00:00.000Z",
      createdAt: "2026-04-09T02:00:00.000Z",
      allowFileUpload: true,
      allowCodeEditor: true,
    },
    {
      id: "assignment-spring-api-contract",
      courseId: "course-spring-lms-api",
      courseTitle: "Spring으로 만드는 LMS API 설계",
      title: "출석 API 계약 문서화",
      prompt: "출석 인증 상태 코드와 요청/응답 스키마를 계약 문서로 정리하세요.",
      dueAt: "2026-04-16T09:00:00.000Z",
      createdAt: "2026-04-09T06:00:00.000Z",
      allowFileUpload: true,
      allowCodeEditor: false,
    },
  ],
  templates: [
    {
      id: "template-next-auth-ts",
      assignmentId: "assignment-next-auth-flow",
      assignmentTitle: "인증 플로우 UI/상태 분리",
      courseId: "course-next-ai-lms",
      courseTitle: "Next.js로 시작하는 AI LMS 프론트엔드",
      editorType: "IDE",
      codeLanguage: "typescript",
      title: "강사 제공 템플릿 - 권한 가드 스캐폴드",
      content: "export function canAccess(role: string, allowedRoles: string[]) {\\n  return allowedRoles.includes(role);\\n}\\n",
      updatedAt: "2026-04-09T08:00:00.000Z",
      updatedById: "instructor-민수-김",
      updatedByName: "민수 김",
    },
  ],
  submissions: [
    {
      id: "submission-1",
      assignmentId: "assignment-next-auth-flow",
      assignmentTitle: "인증 플로우 UI/상태 분리",
      courseId: "course-next-ai-lms",
      courseTitle: "Next.js로 시작하는 AI LMS 프론트엔드",
      studentId: "student-kim-hana",
      studentName: "김하나",
      message: "라우트 가드 컴포넌트와 auth-store 연동 초안을 작성했습니다.",
      code: "export function useRoleGuard() {\\n  return true;\\n}\\n",
      codeLanguage: "typescript",
      editorType: "IDE",
      attachments: [
        {
          id: "file-attachment-1",
          fileName: "auth-flow-notes.md",
          mimeType: "text/markdown",
          sizeBytes: 2389,
        },
      ],
      submittedAt: "2026-04-08T23:00:00.000Z",
      updatedAt: "2026-04-08T23:00:00.000Z",
      reviewStatus: "SUBMITTED",
      revision: 1,
      feedbackHistory: [],
    },
    {
      id: "submission-2",
      assignmentId: "assignment-llm-study-assistant",
      assignmentTitle: "학습 도우미 패널 인터랙션 개선",
      courseId: "course-llm-study-assistant",
      courseTitle: "LLM 학습 도우미 UI 설계",
      studentId: "student-demo-01",
      studentName: "데모 수강생",
      message: "패널 상태 전환과 QA 메모를 첨부합니다.",
      code: "const panelState = { summaryOpen: true, followUpEnabled: true };",
      codeLanguage: "typescript",
      editorType: "IDE",
      attachments: [
        {
          id: "attachment-2",
          fileName: "panel-qa-checklist.xlsx",
          mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          sizeBytes: 11822,
        },
      ],
      submittedAt: "2026-04-09T01:00:00.000Z",
      updatedAt: "2026-04-09T01:00:00.000Z",
      reviewStatus: "NEEDS_REVISION",
      revision: 1,
      feedbackHistory: [
        {
          id: "feedback-1",
          reviewerId: "instructor-민수-김",
          reviewerName: "민수 김",
          messageFormat: "TEXT",
          entryType: "GENERAL",
          message: "상태 전환 조건 분기를 함수로 분리하고 테스트 케이스를 추가해 주세요.",
          code: "function shouldShowFollowUp(summaryOpen: boolean, followUpEnabled: boolean) { return summaryOpen && followUpEnabled; }",
          codeLanguage: "typescript",
          attachments: [],
          createdAt: "2026-04-09T06:00:00.000Z",
        },
      ],
    },
    {
      id: "submission-2-r2",
      assignmentId: "assignment-llm-study-assistant",
      assignmentTitle: "학습 도우미 패널 인터랙션 개선",
      courseId: "course-llm-study-assistant",
      courseTitle: "LLM 학습 도우미 UI 설계",
      studentId: "student-demo-01",
      studentName: "데모 수강생",
      message: "2차 제출입니다. 에러 처리 보완했습니다.",
      code: "export function normalizePanelError(error: unknown) { return String(error); }",
      codeLanguage: "typescript",
      editorType: "IDE",
      attachments: [
        {
          id: "attachment-2-r2",
          fileName: "panel-error-flow-v2.md",
          mimeType: "text/markdown",
          sizeBytes: 2214,
        },
      ],
      submittedAt: "2026-04-09T07:30:00.000Z",
      updatedAt: "2026-04-09T07:30:00.000Z",
      reviewStatus: "NEEDS_REVISION",
      revision: 2,
      feedbackHistory: [
        {
          id: "feedback-2-r2-general",
          reviewerId: "instructor-민수-김",
          reviewerName: "민수 김",
          messageFormat: "MARKDOWN",
          entryType: "GENERAL",
          message: "2차 제출 확인. API 에러 타입 고정이 필요합니다.",
          code: "",
          codeLanguage: "typescript",
          attachments: [],
          createdAt: "2026-04-09T07:50:00.000Z",
        },
      ],
    },
    {
      id: "submission-2-r3",
      assignmentId: "assignment-llm-study-assistant",
      assignmentTitle: "학습 도우미 패널 인터랙션 개선",
      courseId: "course-llm-study-assistant",
      courseTitle: "LLM 학습 도우미 UI 설계",
      studentId: "student-demo-01",
      studentName: "데모 수강생",
      message: "3차 제출입니다. 타입 가드 반영 완료했습니다.",
      code: "export function hasMessage(error: unknown): error is { message: unknown } { return typeof error === 'object' && error !== null && 'message' in error; }",
      codeLanguage: "typescript",
      editorType: "IDE",
      attachments: [
        {
          id: "attachment-2-r3",
          fileName: "panel-tests-v3.md",
          mimeType: "text/markdown",
          sizeBytes: 2491,
        },
      ],
      submittedAt: "2026-04-09T08:15:00.000Z",
      updatedAt: "2026-04-09T08:15:00.000Z",
      reviewStatus: "REVIEWED",
      revision: 3,
      feedbackHistory: [
        {
          id: "feedback-2-r3-general",
          reviewerId: "instructor-민수-김",
          reviewerName: "민수 김",
          messageFormat: "TEXT",
          entryType: "GENERAL",
          message: "반영 완료 확인했습니다. 리뷰 완료 처리합니다.",
          code: "",
          codeLanguage: "typescript",
          attachments: [],
          createdAt: "2026-04-09T08:30:00.000Z",
        },
      ],
    },
    {
      id: "submission-3",
      assignmentId: "assignment-next-course-filter",
      assignmentTitle: "서버 필터 스키마 안정화",
      courseId: "course-next-ai-lms",
      courseTitle: "Next.js로 시작하는 AI LMS 프론트엔드",
      studentId: "student-demo-01",
      studentName: "데모 수강생",
      message: "필터 응답 스키마 초안 제출입니다.",
      code: "export interface FilterResponse { items: unknown[]; page: number; totalPages: number; }",
      codeLanguage: "typescript",
      editorType: "IDE",
      attachments: [
        {
          id: "attachment-3",
          fileName: "filter-contract-v1.md",
          mimeType: "text/markdown",
          sizeBytes: 1820,
        },
      ],
      submittedAt: "2026-04-09T03:00:00.000Z",
      updatedAt: "2026-04-09T03:00:00.000Z",
      reviewStatus: "SUBMITTED",
      revision: 1,
      feedbackHistory: [],
    },
    {
      id: "submission-4",
      assignmentId: "assignment-spring-api-contract",
      assignmentTitle: "출석 API 계약 문서화",
      courseId: "course-spring-lms-api",
      courseTitle: "Spring으로 만드는 LMS API 설계",
      studentId: "student-kim-hana",
      studentName: "김하나",
      message: "요청/응답 DTO와 상태 코드 표를 정리했습니다.",
      code: "attendance_check_in.md 문서 기반 계약 정리 제출",
      codeLanguage: "markdown",
      editorType: "NOTE",
      attachments: [
        {
          id: "file-attachment-4",
          fileName: "attendance-api-contract.md",
          mimeType: "text/markdown",
          sizeBytes: 3275,
        },
      ],
      submittedAt: "2026-04-09T04:00:00.000Z",
      updatedAt: "2026-04-09T04:00:00.000Z",
      reviewStatus: "REVIEWED",
      revision: 1,
      feedbackHistory: [
        {
          id: "feedback-4-general",
          reviewerId: "instructor-민수-김",
          reviewerName: "민수 김",
          messageFormat: "TEXT",
          entryType: "GENERAL",
          message: "DTO 필드 정의가 명확합니다. 에러코드 예시 2개만 추가하면 충분합니다.",
          code: "",
          codeLanguage: "markdown",
          attachments: [],
          createdAt: "2026-04-09T04:10:00.000Z",
        },
      ],
    },
  ],
  timeline: [
    {
      id: "timeline-1",
      submissionId: "submission-1",
      type: "SUBMITTED",
      actorId: "student-kim-hana",
      actorName: "김하나",
      createdAt: "2026-04-08T23:00:00.000Z",
      note: "초기 제출",
    },
    {
      id: "timeline-2",
      submissionId: "submission-2",
      type: "SUBMITTED",
      actorId: "student-demo-01",
      actorName: "데모 수강생",
      createdAt: "2026-04-09T01:00:00.000Z",
      note: "초기 제출",
    },
    {
      id: "timeline-3",
      submissionId: "submission-2",
      type: "COMMENTED",
      actorId: "instructor-민수-김",
      actorName: "민수 김",
      createdAt: "2026-04-09T06:00:00.000Z",
      note: "코드 리팩터링 포인트 피드백 등록",
    },
    {
      id: "timeline-4",
      submissionId: "submission-2",
      type: "REVIEW_STATUS_CHANGED",
      actorId: "instructor-민수-김",
      actorName: "민수 김",
      createdAt: "2026-04-09T06:05:00.000Z",
      note: "리팩터링 가이드 보강 필요",
    },
    {
      id: "timeline-6",
      submissionId: "submission-2-r2",
      type: "RESUBMITTED",
      actorId: "student-demo-01",
      actorName: "데모 수강생",
      createdAt: "2026-04-09T07:30:00.000Z",
      note: "2차 재제출",
    },
    {
      id: "timeline-10",
      submissionId: "submission-2-r3",
      type: "RESUBMITTED",
      actorId: "student-demo-01",
      actorName: "데모 수강생",
      createdAt: "2026-04-09T08:15:00.000Z",
      note: "3차 재제출",
    },
    {
      id: "timeline-12",
      submissionId: "submission-2-r3",
      type: "REVIEW_STATUS_CHANGED",
      actorId: "instructor-민수-김",
      actorName: "민수 김",
      createdAt: "2026-04-09T08:30:00.000Z",
      note: "리뷰 완료",
    },
    {
      id: "timeline-13",
      submissionId: "submission-3",
      type: "SUBMITTED",
      actorId: "student-demo-01",
      actorName: "데모 수강생",
      createdAt: "2026-04-09T03:00:00.000Z",
      note: "필터 스키마 과제 1차 제출",
    },
    {
      id: "timeline-14",
      submissionId: "submission-4",
      type: "SUBMITTED",
      actorId: "student-kim-hana",
      actorName: "김하나",
      createdAt: "2026-04-09T04:00:00.000Z",
      note: "출석 API 계약 문서 과제 제출",
    },
    {
      id: "timeline-16",
      submissionId: "submission-4",
      type: "REVIEW_STATUS_CHANGED",
      actorId: "instructor-민수-김",
      actorName: "민수 김",
      createdAt: "2026-04-09T04:10:00.000Z",
      note: "리뷰 완료",
    },
  ],
  videos: [
    {
      id: "video-1",
      courseId: "course-next-ai-lms",
      courseTitle: "Next.js로 시작하는 AI LMS 프론트엔드",
      title: "강사 피드백 라이브 1회차",
      fileName: "feedback-session-1.mp4",
      mimeType: "video/mp4",
      sizeBytes: 128440221,
      uploadedAt: "2026-04-08T03:00:00.000Z",
      uploadedById: "instructor-민수-김",
      uploadedByName: "민수 김",
    },
  ],
};

const fileSeedData: StoredFileRecord[] = [
  {
    fileId: "file-attachment-1",
    ownerId: "student-kim-hana",
    fileName: "auth-flow-notes.md",
    bucketKey: "student-kim-hana/file-attachment-1/auth-flow-notes.md",
    contentType: "text/markdown",
    size: 2389,
    checksum: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    status: "COMPLETED",
    uploadUrl: "https://storage.mock.local/upload/student-kim-hana%2Ffile-attachment-1%2Fauth-flow-notes.md?signature=dev-signature",
    downloadUrl: "https://storage.mock.local/download/student-kim-hana%2Ffile-attachment-1%2Fauth-flow-notes.md",
    createdAt: "2026-04-08T22:50:00.000Z",
    completedAt: "2026-04-08T22:51:00.000Z",
  },
  {
    fileId: "file-attachment-4",
    ownerId: "student-kim-hana",
    fileName: "attendance-api-contract.md",
    bucketKey: "student-kim-hana/file-attachment-4/attendance-api-contract.md",
    contentType: "text/markdown",
    size: 3275,
    checksum: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    status: "COMPLETED",
    uploadUrl: "https://storage.mock.local/upload/student-kim-hana%2Ffile-attachment-4%2Fattendance-api-contract.md?signature=dev-signature",
    downloadUrl: "https://storage.mock.local/download/student-kim-hana%2Ffile-attachment-4%2Fattendance-api-contract.md",
    createdAt: "2026-04-09T03:55:00.000Z",
    completedAt: "2026-04-09T03:56:00.000Z",
  },
  {
    fileId: "file-pending-1",
    ownerId: "student-demo-01",
    fileName: "panel-tests-v4.md",
    bucketKey: "student-demo-01/file-pending-1/panel-tests-v4.md",
    contentType: "text/markdown",
    size: 2500,
    checksum: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
    status: "PENDING",
    uploadUrl: "https://storage.mock.local/upload/student-demo-01%2Ffile-pending-1%2Fpanel-tests-v4.md?signature=dev-signature",
    createdAt: "2026-04-10T00:00:00.000Z",
  },
];

const userSeedData: RawUserSeed[] = adminSeedData.users.map((user, index) => ({
  userId: user.userId,
  email: `${user.userId}@koreait.academy`.toLowerCase(),
  password: "password123",
  userName: user.userName,
  birthDate: user.birthDate,
  title: user.title,
  role:
    user.defaultRole === "INSTRUCTOR"
      ? "instructor"
      : user.defaultRole === "ASSISTANT"
        ? "assistant"
        : "student",
  createdAt: new Date(Date.UTC(2026, 3, 1 + index)).toISOString(),
}));

userSeedData.unshift({
  userId: "admin-root",
  email: "admin-root@koreait.academy",
  password: "password123",
  userName: "로컬 관리자",
  birthDate: "1985-01-01",
  title: "Administrator",
  role: "admin",
  createdAt: "2026-04-01T00:00:00.000Z",
});

const courseSeedData: CoursesDatabase = {
  featuredCourseId: "course-next-ai-lms",
  categories: ["전체", "프론트엔드", "백엔드", "AI 활용", "데이터", "디자인 시스템"],
  courses: [
    {
      id: "course-next-ai-lms",
      slug: "nextjs-ai-lms-foundation",
      title: "Next.js로 시작하는 AI LMS 프론트엔드",
      subtitle: "강의 탐색, 상세, 수강 흐름을 실제 제품 구조로 설계합니다.",
      description:
        "마케팅 페이지가 아니라 실제 서비스 화면을 기준으로 App Router, 인증, 강의 목록, 상세, 수강 플레이어까지 이어지는 기반을 만듭니다.",
      category: "프론트엔드",
      tags: ["Next.js", "TypeScript", "App Router"],
      level: "중급",
      durationLabel: "18시간 20분",
      lessonCount: 42,
      priceLabel: "월 구독 포함",
      rating: 4.9,
      reviewCount: 182,
      enrollmentCount: 1240,
      thumbnailTone: "from-[#10302b] via-[#145c54] to-[#d7f3eb]",
      instructor: {
        name: "민수 김",
        title: "Frontend Engineer",
      },
      enrollmentStatus: "ACTIVE",
      isFeatured: true,
      learningPoints: [
        "App Router 기반 서비스 화면 구조를 실제 LMS 흐름에 맞춰 설계합니다.",
        "강의 목록, 상세, 플레이어 접근 정책을 프론트 기준으로 연결합니다.",
        "인증 저장소와 API 계층을 제품 구조에 맞게 분리합니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-next-1",
          title: "서비스형 LMS 정보 구조 잡기",
          durationLabel: "18분",
          isPreview: true,
        },
        {
          id: "lesson-next-2",
          title: "App Router로 라우트 그룹 나누기",
          durationLabel: "26분",
        },
      ],
      classScope: "nextjs로-시작하는-ai-lms-프론트엔드",
      lifecycleStatus: "ACTIVE",
      sectionLabel: "1반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-04-20",
      endDate: "2026-07-12",
      enrollmentStartDate: "2026-04-01",
      enrollmentEndDate: "2026-04-30",
    },
    {
      id: "course-react-state",
      slug: "react-state-patterns",
      title: "React 상태 설계 패턴",
      subtitle: "UI 상태와 서버 상태를 분리해서 다루는 실전 패턴",
      description: "Zustand와 폼 상태를 분리해 유지보수 가능한 학습 제품 UI를 설계합니다.",
      category: "프론트엔드",
      tags: ["React", "Zustand", "Architecture"],
      level: "중급",
      durationLabel: "9시간 40분",
      lessonCount: 27,
      priceLabel: "₩69,000",
      rating: 4.8,
      reviewCount: 96,
      enrollmentCount: 860,
      thumbnailTone: "from-[#1e293b] via-[#334155] to-[#cbd5e1]",
      instructor: {
        name: "정하늘",
        title: "Senior Frontend Developer",
      },
      enrollmentStatus: "NOT_ENROLLED",
      learningPoints: [
        "서버 상태와 UI 상태를 분리하는 기준을 익힙니다.",
        "Zustand와 폼 상태를 섞지 않는 구조를 배웁니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-react-1",
          title: "로컬 상태와 서버 상태 경계 설정",
          durationLabel: "21분",
          isPreview: true,
        },
      ],
      classScope: "react-상태-설계-패턴",
      lifecycleStatus: "ACTIVE",
      sectionLabel: "2반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-04-27",
      endDate: "2026-07-19",
      enrollmentStartDate: "2026-04-01",
      enrollmentEndDate: "2026-05-10",
    },
    {
      id: "course-spring-lms-api",
      slug: "spring-lms-api-design",
      title: "Spring으로 만드는 LMS API 설계",
      subtitle: "강의, 수강, 진도, 권한 모델링을 한 번에 정리",
      description: "강의 목록 API와 수강 플레이어 API를 분리하고 권한 체크를 안정적으로 설계합니다.",
      category: "백엔드",
      tags: ["Spring", "JPA", "Authorization"],
      level: "중급",
      durationLabel: "14시간 10분",
      lessonCount: 35,
      priceLabel: "₩89,000",
      rating: 4.7,
      reviewCount: 73,
      enrollmentCount: 670,
      thumbnailTone: "from-[#2e1065] via-[#6d28d9] to-[#ede9fe]",
      instructor: {
        name: "이도현",
        title: "Backend Architect",
      },
      enrollmentStatus: "PENDING",
      learningPoints: [
        "LMS 도메인에서 강의/수강/진도 모델을 분리합니다.",
        "권한 체크를 프론트와 백엔드에서 동시에 다루는 방식을 정리합니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-spring-1",
          title: "수강 상태 모델과 권한 매트릭스",
          durationLabel: "28분",
          isPreview: true,
        },
      ],
      classScope: "spring으로-만드는-lms-api-설계",
      lifecycleStatus: "PENDING",
      sectionLabel: "3반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-05-04",
      endDate: "2026-07-26",
      enrollmentStartDate: "2026-04-01",
      enrollmentEndDate: "2026-05-20",
    },
    {
      id: "course-llm-study-assistant",
      slug: "llm-study-assistant-ui",
      title: "LLM 학습 도우미 UI 설계",
      subtitle: "AI를 수강 흐름 안에 자연스럽게 붙이는 방법",
      description: "요약, 쉬운 설명, 예상 문제 생성 기능을 플레이어 맥락에 맞게 보조 패널로 설계합니다.",
      category: "AI 활용",
      tags: ["LLM", "Prompt UX", "Education"],
      level: "입문",
      durationLabel: "7시간 25분",
      lessonCount: 18,
      priceLabel: "₩59,000",
      rating: 4.9,
      reviewCount: 121,
      enrollmentCount: 1130,
      thumbnailTone: "from-[#3f6212] via-[#84cc16] to-[#ecfccb]",
      instructor: {
        name: "박서윤",
        title: "AI Product Designer",
      },
      enrollmentStatus: "ACTIVE",
      learningPoints: [
        "AI 기능을 메인 학습 흐름을 방해하지 않게 배치합니다.",
        "요약, 쉬운 설명, 퀴즈 생성 UI를 플레이어 맥락에 맞춰 설계합니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-llm-1",
          title: "보조 패널형 AI UX의 기본 원칙",
          durationLabel: "15분",
          isPreview: true,
        },
      ],
      classScope: "llm-학습-도우미-ui-설계",
      lifecycleStatus: "ACTIVE",
      sectionLabel: "4반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-05-11",
      endDate: "2026-08-02",
      enrollmentStartDate: "2026-04-01",
      enrollmentEndDate: "2026-05-30",
    },
    {
      id: "course-sql-learning-analytics",
      slug: "sql-learning-analytics",
      title: "SQL로 보는 학습 분석",
      subtitle: "학생 위험도와 이탈 신호를 데이터로 읽는 법",
      description: "LMS 로그를 기반으로 학습 진도, 과제 제출, 재생 패턴을 조회하는 분석 쿼리를 설계합니다.",
      category: "데이터",
      tags: ["SQL", "Analytics", "BI"],
      level: "입문",
      durationLabel: "6시간 50분",
      lessonCount: 21,
      priceLabel: "₩49,000",
      rating: 4.6,
      reviewCount: 58,
      enrollmentCount: 430,
      thumbnailTone: "from-[#083344] via-[#0891b2] to-[#cffafe]",
      instructor: {
        name: "한지민",
        title: "Data Analyst",
      },
      enrollmentStatus: "COMPLETED",
      learningPoints: [
        "학습 로그를 기반으로 주요 지표를 읽는 방법을 배웁니다.",
        "위험 학생 탐지를 위한 기본 지표 설계를 다룹니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-sql-1",
          title: "학습 이탈 신호 정의하기",
          durationLabel: "18분",
          isPreview: true,
        },
      ],
      classScope: "sql로-보는-학습-분석",
      lifecycleStatus: "ACTIVE",
      sectionLabel: "5반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-05-18",
      endDate: "2026-08-09",
      enrollmentStartDate: "2026-04-01",
      enrollmentEndDate: "2026-06-10",
    },
    {
      id: "course-design-system-edu",
      slug: "design-system-for-education",
      title: "교육 제품용 디자인 시스템",
      subtitle: "운영 화면과 학습 화면을 한 톤으로 묶는 기준",
      description: "관리자 화면과 학습 화면이 함께 있는 제품에서 디자인 토큰과 컴포넌트 기준을 정리합니다.",
      category: "디자인 시스템",
      tags: ["Design System", "Tokens", "UI"],
      level: "중급",
      durationLabel: "8시간 15분",
      lessonCount: 24,
      priceLabel: "₩79,000",
      rating: 4.8,
      reviewCount: 64,
      enrollmentCount: 350,
      thumbnailTone: "from-[#4c0519] via-[#be185d] to-[#fbcfe8]",
      instructor: {
        name: "윤태호",
        title: "Product Designer",
      },
      enrollmentStatus: "NOT_ENROLLED",
      learningPoints: [
        "관리자와 학생 화면을 함께 고려한 토큰 체계를 설계합니다.",
        "컴포넌트 계층과 문서화 전략을 함께 정리합니다.",
      ],
      curriculumPreview: [
        {
          id: "lesson-design-1",
          title: "토큰 우선 설계",
          durationLabel: "19분",
          isPreview: true,
        },
      ],
      classScope: "교육-제품용-디자인-시스템",
      lifecycleStatus: "ACTIVE",
      sectionLabel: "6반",
      roomLabel: "8층 AI 강의실",
      capacity: 30,
      startDate: "2026-05-25",
      endDate: "2026-08-16",
      enrollmentStartDate: "2026-04-01",
      enrollmentEndDate: "2026-06-20",
    },
  ],
};

const enrollmentSeedData: EnrollmentsDatabase = {
  enrollments: [
    {
      enrollmentId: "enrollment-student-demo-next",
      courseId: "course-next-ai-lms",
      userId: "student-demo-01",
      status: "ACTIVE",
      enrolledAt: "2026-04-05T00:00:00.000Z",
      updatedAt: "2026-04-05T00:00:00.000Z",
    },
    {
      enrollmentId: "enrollment-student-demo-llm",
      courseId: "course-llm-study-assistant",
      userId: "student-demo-01",
      status: "ACTIVE",
      enrolledAt: "2026-04-06T00:00:00.000Z",
      updatedAt: "2026-04-06T00:00:00.000Z",
    },
    {
      enrollmentId: "enrollment-student-hana-next",
      courseId: "course-next-ai-lms",
      userId: "student-kim-hana",
      status: "ACTIVE",
      enrolledAt: "2026-04-04T00:00:00.000Z",
      updatedAt: "2026-04-04T00:00:00.000Z",
    },
    {
      enrollmentId: "enrollment-student-hana-spring",
      courseId: "course-spring-lms-api",
      userId: "student-kim-hana",
      status: "PENDING",
      enrolledAt: "2026-04-08T00:00:00.000Z",
      updatedAt: "2026-04-08T00:00:00.000Z",
    },
    {
      enrollmentId: "enrollment-student-jisoo-llm",
      courseId: "course-llm-study-assistant",
      userId: "student-lee-jisoo",
      status: "ACTIVE",
      enrolledAt: "2026-04-07T00:00:00.000Z",
      updatedAt: "2026-04-07T00:00:00.000Z",
    },
  ],
};

const attendanceSeedData: AttendanceDatabase = {
  programName: "AI 서비스 개발자 국비지원 과정",
  expectedCodeLength: 6,
  scheduleTemplates: [
    {
      key: "orientation",
      title: "오리엔테이션 및 학습 가이드",
      categoryLabel: "운영",
      dayOffset: 0,
      timeLabel: "09:30 - 11:00",
      locationLabel: "온라인 라이브 · Zoom A",
      visibilityType: "global",
      requiresAttendanceCheck: false,
    },
    {
      key: "daily-check-in",
      title: "오늘 출석 체크",
      categoryLabel: "필수 출석",
      dayOffset: 0,
      timeLabel: "00:00 - 23:59",
      locationLabel: "8층 AI 강의실",
      visibilityType: "class",
      requiresAttendanceCheck: true,
      supportsCodeCheckIn: true,
      attendanceWindowStartTime: "00:00",
      attendanceWindowEndTime: "23:59",
    },
    {
      key: "frontend-lab",
      title: "프론트엔드 실습 랩",
      categoryLabel: "수업",
      dayOffset: 0,
      timeLabel: "10:00 - 12:30",
      locationLabel: "8층 AI 강의실",
      visibilityType: "class",
      requiresAttendanceCheck: false,
    },
    {
      key: "career-coaching",
      title: "커리어 코칭 데이",
      categoryLabel: "특강",
      dayOffset: 1,
      timeLabel: "14:00 - 16:00",
      locationLabel: "온라인 라이브 · Meet",
      visibilityType: "global",
      requiresAttendanceCheck: false,
    },
    {
      key: "missed-check-in",
      title: "이전 출석 체크",
      categoryLabel: "필수 출석",
      dayOffset: -1,
      timeLabel: "13:00 - 13:20",
      locationLabel: "8층 AI 강의실",
      visibilityType: "class",
      requiresAttendanceCheck: true,
      supportsCodeCheckIn: true,
      attendanceWindowStartTime: "13:00",
      attendanceWindowEndTime: "13:20",
    },
  ],
  checkInCodeByScheduleKey: {
    "daily-check-in": "381924",
    "missed-check-in": "143250",
  },
  records: [
    {
      userId: "student-demo-01",
      scheduleKey: "missed-check-in",
      attendanceStatus: "ABSENT",
    },
  ],
};

export function createFrontAlignedAdminSeed(): AdminSeedData {
  return clone(adminSeedData);
}

export function createFrontAlignedUsersDatabase(): UsersDatabase {
  const users: StoredUserRecord[] = userSeedData.map((user) => ({
    userId: user.userId,
    email: user.email,
    passwordHash: "",
    passwordSalt: "",
    userName: user.userName,
    birthDate: user.birthDate,
    title: user.title,
    role: user.role,
    createdAt: user.createdAt,
    updatedAt: user.createdAt,
  }));
  return {
    users: clone(users),
  };
}

export function createFrontAlignedUserSeeds(): RawUserSeed[] {
  return clone(userSeedData);
}

export function createFrontAlignedCoursesDatabase(): CoursesDatabase {
  return clone(courseSeedData);
}

export function createFrontAlignedEnrollmentsDatabase(): EnrollmentsDatabase {
  return clone(enrollmentSeedData);
}

export function createFrontAlignedAttendanceDatabase(): AttendanceDatabase {
  return clone(attendanceSeedData);
}

export function createFrontAlignedAssignmentDatabase(): AssignmentDatabase {
  return clone(assignmentSeedData);
}

export function createFrontAlignedFileRecords(): StoredFileRecord[] {
  return clone(fileSeedData);
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}
